package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;

import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    ShimPluginRegistry shimPluginRegistry = new ShimPluginRegistry(flutterEngine);
      com.aloisdeniel.flutter.appcenter.AppcenterPlugin.registerWith(shimPluginRegistry.registrarFor("com.aloisdeniel.flutter.appcenter.AppcenterPlugin"));
      com.aloisdeniel.flutter.appcenter_analytics.AppcenterAnalyticsPlugin.registerWith(shimPluginRegistry.registrarFor("com.aloisdeniel.flutter.appcenter_analytics.AppcenterAnalyticsPlugin"));
      com.aloisdeniel.flutter.appcenter_crashes.AppcenterCrashesPlugin.registerWith(shimPluginRegistry.registrarFor("com.aloisdeniel.flutter.appcenter_crashes.AppcenterCrashesPlugin"));
    flutterEngine.getPlugins().add(new com.github.hanabi1224.flutter_appcenter_bundle.FlutterAppcenterBundlePlugin());
  }
}
